server:
  port: 8999
spring:
  application:
    name: backend
  # spring provided properties
  datasource:
    url: jdbc:mysql://${app.database.host}:${app.database.port}/${app.database.name}?serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=FALSE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:  ${app.database.username}
    password: ${app.database.password}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
#          格式化sql
        format_sql: true
#       指定引擎
        dialect:
          storage_engine: innodb
#          展示sql
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: user
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Database connection properties. The default values should work with the docker-compose file provided in the repository
# If you want to change this, make sure to also update the docker-compose file accordingly
app:
  database:
    name: starter-kit-db
    username: user
    password: password
    host: localhost
    port: 3316
  allowed-origins: http://localhost:3000
  application-name: starter-kit
  base-url: http://localhost:8080
  login-page-url: ${app.base-url}/auth/login
  login-success-url: ${app.base-url}/auth/login-success

  s3:
    bucket-name: springboot-nextjs-bucket
    access-key: f2xX1laGDPAOtVgv
    secret-key: iHu9NBnTSloWd1scrx9zXdlu8MGMS2qyPYdLu6Bk
  # 对象存储使用 tebi.io
#    https://client.tebi.io/buckets/
    base-url: http://s3.tebi.io
    region: Germany,Europe
    storage-class: STANDARD

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
      port: 8899

  #common logging levels that you might want to use in development, just uncomment the ones you want to use and set the level you want
logging:
  level:
    org:
      springframework:
        security: DEBUG
  #logging.level.org.springframework.web=INFO
  #logging.level.org.hibernate=TRACE
  #logging.level.org.hibernate.type.descriptor.sql=trace
  #logging.level.org.hibernate.SQL=DEBUG
  #logging.level.org.hibernate.type=TRACE